### ISSUE TITLE
 Unknown slot number of character 

### ISSUE THREAD

**Issue by 5dash** [ElegantLaTeX/ElegantNote#10]
`xelatex`编译疯狂报` Unknown slot number of character `的warring，windows10 需要设置字体吗？
![image](https://user-images.githubusercontent.com/53204626/69729285-044ee280-1161-11ea-9e93-55bd580771e2.png)

**Comment by EthanDeng** [comment]
这个是 microtype 的问题，我把这个宏包去掉了。

**Comment by andy123t** [comment]
运行ElegantNote时遇到的两个小问题，一，目录生成时，“目录”是靠左的，想让目录居中，加\renewcommand{\contentsname}{\centerline{目录}}，“目录”居中但与目录内容间距过大；二，设备选择如果是screen，页码是居中的，但在normal (A4) 模式下，页码不居中。
