### ISSUE TITLE
Centering of contentsname and page numbers

### ISSUE THREAD

**Issue by andy123t** [ElegantLaTeX/ElegantNote#11]
一，目录生成时，“目录”是靠左的，想让目录居中，加\renewcommand{\contentsname}{\centerline{目录}}，“目录”居中但与目录内容间距过大；

二，设备选择如果是screen，页码是居中的，但在normal (A4) 模式下，页码不居中。

**Comment by EthanDeng** [comment]
第一个问题，目录居中可以使用 
```tex
\renewcommand*\contentsname{\centering 目录}
```
或者
```tex
\renewcommand*\contentsname{\hfill 目录 \hfill}
```
这样 都不会增加距离，或者还可以借助其他宏包实现，比如 `tocloft`。有人说这个宏包和之前的方法有冲突，自己选一个就好了。

**Comment by EthanDeng** [comment]
第二个问题其实是算 bug，产生这个的原因是因为我的页眉页脚放在版面设置的前面了，我对这个有点印象，但是没仔细看过，确实是因为这个导致的，我这就去更新一下。

**Comment by EthanDeng** [comment]
上述两个都已应用到最新版本中，感谢反馈！
