### ISSUE TITLE
字体设置问题

### ISSUE THREAD

**Issue by muyuuuu** [ElegantLaTeX/ElegantNote#15]
# 问题一：全局字体设置问题

`\documentclass[geye, pad, blue, 8pt]{elegantnote}`和`\documentclass[geye, pad, blue, 14pt]{elegantnote}`全文字体大小没变化啊，永远都是那么大。（删除了辅助文件）

# 问题二：更改字体的问题

我`\setmainfont{Source Han Serif CN}`使用思源宋体，但`remark`环境里的楷体也发生了改变，我不想让他改变，只改变正文的字体，有办法么。
![image](https://user-images.githubusercontent.com/43681138/75156348-e76c8000-574c-11ea-95ae-06da7b1abc78.png)

**Comment by muyuuuu** [comment]
补充一点：在不动`cls`文件的前提下.....有办法补救上面的两个问题么

**Comment by EthanDeng** [comment]
问题一，请保证你的 cls 是最新的，我这边没有问题。
问题二，我这边改用其他字体，remark 的楷体是不会变的，所以可能和你的系统有关系。另外英文字体会变回 cm，因此不推荐这样修改字体。等下一个版本，我会把 book 里面的字体设置应用到 Note 里面，并提供设置方法的说明。

**Comment by muyuuuu** [comment]
windows10+texlive2019+xelatex

意思是，我要更新下宏包么。`texdoc elegantnote`显示版本是`2.10`。

![image](https://user-images.githubusercontent.com/43681138/75163891-ecd0c700-575a-11ea-97ae-579ecc4b72cb.png)

**Comment by muyuuuu** [comment]
果然我该更新了..........抱歉。

**Comment by muyuuuu** [comment]
在`tlmgr update --self --all`后到`2.20`，那俩问题都没有了，我仿佛成了来捣乱的，抱歉。

**Comment by eastynchen** [comment]
在`cls`文档中设置字体为`微软雅黑`或`思源黑体`（主要用于`screen`模式），应该怎么操作？

**Comment by EthanDeng** [comment]
> 在`cls`文档中设置字体为`微软雅黑`或`思源黑体`（主要用于`screen`模式），应该怎么操作？

参考最新版，使用 `chinesefont=none`，然后在导言区设置中文字体，和 Book 模板字体设置一样。
