### ISSUE TITLE
email

### ISSUE THREAD

**Issue by houzf** [ElegantLaTeX/ElegantNote#16]
在\institute{}之后，可否增加一个功能，添加email?如下面的所示：
\email{aaa@gmail.com}

**Comment by EthanDeng** [comment]
在 3.10 版本，你可以使用 `\bioinfo{邮箱}{aaa@gmail.com}`。

**Comment by houzf** [comment]
\bioinfo定义在egantbook.cls里了，但是在elegantnote.cls没有。

**Comment by sikouhjw** [comment]
模仿 ElegantBook 中 `\email` 的定义就好了
```latex
\newcommand\email[1]{\href{mailto:#1}{\nolinkurl{#1}}}
```

**Comment by houzf** [comment]
谢谢。
\institute{aaa研究所 \\ \email{aaa@gmail.com}}
