### ISSUE TITLE
Python Style Code

### ISSUE THREAD

**Issue by MingFengX** [ElegantLaTeX/ElegantNote#19]
Can we have  a python style code? 
![image](https://user-images.githubusercontent.com/43533219/83354743-3a2d8780-a38d-11ea-91be-595ff4a592e8.png)

Below is MWE. it is a latex style, which is not what I want……

```tex
\documentclass{elegantnote}
\begin{document}
\begin{lstlisting}
import numpy as np
from scipy.stats import uniform, norm
from src.iteration import iter_reg

n = 100
p = 10
sigma = 1

x = uniform.rvs(loc = -1, scale = 2, size = n * p).reshape(n, p)
epsilon = norm.rvs(scale = sigma, size = n).reshape(n, 1)
beta = norm.rvs(scale = 0.5, size = p + 1).reshape(p + 1, 1)
z = np.c_[np.ones((n, 1)), x]
y = np.dot(z, beta) + epsilon

model = iter_reg(x, y)
acu = model.fit()

print(acu)
\end{lstlisting}
\end{document}
```

**Comment by EthanDeng** [comment]
You can set `language` option for `lstlisting` environment.

```tex
\begin{lstlisting}[language=Python]
....
\end{lstlisting}
```

**Comment by MingFengX** [comment]
emm not much changed.
![image](https://user-images.githubusercontent.com/43533219/83355294-313eb500-a391-11ea-8c05-28abc8d514ab.png)
I expected a sublime 3 or IDLE style. Maybe I expected too much.……

**Comment by EthanDeng** [comment]
you can modify the settings for `language=Python`, which you can refer to [python-comments-not-highlighted-with-lstlisting](https://tex.stackexchange.com/questions/483971/python-comments-not-highlighted-with-lstlisting) to customize.

**Comment by MingFengX** [comment]
No much color changing for there are few keywords. No more comments. Thanks for your attention.
