### ISSUE TITLE
Texlive 2017 会存在 gbt7714.sty 文件缺失的问题

### ISSUE THREAD

**Issue by feiyuxiaoThu** [ElegantLaTeX/ElegantNote#20]
下载了 gbt7714.sty 文件放在目录下，采用 xelatex 编译通过
（一个可用的 sty 文件地址  [https://gitee.com/walkeraguo/gbt7714-bibtex-style/blob/master/gbt7714.sty#](url)）

**Comment by sikouhjw** [comment]
最好就不要用 `TeX Live 2017` 了，有什么理由一定要用旧版本的呢？

**Comment by feiyuxiaoThu** [comment]
主要是也用的习惯了，感觉也没更新到最新版的必要（文档里说的似乎是 TeX Live 2018 可用，大概是模板采用了一些新特性吧~），谢谢！
