### ISSUE TITLE
能否增加demo?

### ISSUE THREAD

**Issue by qqlovekerry** [ElegantLaTeX/ElegantNote#22]
目前github的文档中只有tex文档和cls文件，可否增加编译成功的pdf文件，方便感兴趣的用户选择。

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantNote/releases

**Comment by EthanDeng** [comment]
在 [release](https://github.com/ElegantLaTeX/ElegantNote/releases) 这里有。

**Comment by EthanDeng** [comment]
如上网址中是模板的使用说明，也是用当前模板制作的 PDF 文件，供参考。
