### ISSUE TITLE
能否增加使用biblatex来处理参考文献的方法

### ISSUE THREAD

**Issue by zalois** [ElegantLaTeX/ElegantNote#23]
建议增加一个用biblatex处理参考文献的方法，毕竟bibtex应该慢慢会被抛弃的。

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/93

**Comment by zalois** [comment]
> [ElegantLaTeX/ElegantBook#93](https://github.com/ElegantLaTeX/ElegantBook/issues/93)

谢谢你，看到了，我看看学习一下。

**Comment by zalois** [comment]
> [ElegantLaTeX/ElegantBook#93](https://github.com/ElegantLaTeX/ElegantBook/issues/93)

我把模板中用关参考文献的段落注释掉了，现在可以用biblatex来处理参考文献了。谢谢你的关注。期待大佬更新模板，增加biblatex支持。还有提醒下大佬，book中文示例中，有关参考文献的叙述还是bibtex的，没有对应更新。

**Comment by sikouhjw** [comment]
> > [ElegantLaTeX/ElegantBook#93](https://github.com/ElegantLaTeX/ElegantBook/issues/93)
> 
> 我把模板中用关参考文献的段落注释掉了，现在可以用biblatex来处理参考文献了。谢谢你的关注。期待大佬更新模板，增加biblatex支持。还有提醒下大佬，book中文示例中，有关参考文献的叙述还是bibtex的，没有对应更新。

还没更新到4.x，所以说明手册没更新

**Comment by zalois** [comment]
> > > [ElegantLaTeX/ElegantBook#93](https://github.com/ElegantLaTeX/ElegantBook/issues/93)
> > 
> > 
> > 我把模板中用关参考文献的段落注释掉了，现在可以用biblatex来处理参考文献了。谢谢你的关注。期待大佬更新模板，增加biblatex支持。还有提醒下大佬，book中文示例中，有关参考文献的叙述还是bibtex的，没有对应更新。
> 
> 还没更新到4.x，所以说明手册没更新

知道了，感谢。
