### ISSUE TITLE
请问如何设置页面长度...

### ISSUE THREAD

**Issue by BlockChanZJ** [ElegantLaTeX/ElegantNote#25]
笔记的页面长度感觉太小，想调长一点

**Comment by sikouhjw** [comment]
```tex
\documentclass[device=pad]{elegantnote} % ipad screen size
\documentclass[device=kindle]{elegantnote} % kindle screen size
\documentclass[device=pc]{elegantnote} % double pages for pc
\documentclass[device=normal]{elegantnote} % a4 normal page
\documentclass[device=screen]{elegantnote} % 4:3 PPT size
```
都不够用？
那就自己改 `\geometry`

**Comment by BlockChanZJ** [comment]
> ```
> \documentclass[device=pad]{elegantnote} % ipad screen size
> \documentclass[device=kindle]{elegantnote} % kindle screen size
> \documentclass[device=pc]{elegantnote} % double pages for pc
> \documentclass[device=normal]{elegantnote} % a4 normal page
> \documentclass[device=screen]{elegantnote} % 4:3 PPT size
> ```
> 
> 都不够用？
> 那就自己改 `\geometry`

好的谢谢
