### ISSUE TITLE
使用https://elegantlatex.org/en/示例编译失败

### ISSUE THREAD

**Issue by tiange1949** [ElegantLaTeX/ElegantNote#27]
- 编译方式：xelatex

- 安装方式：通过Windows 10命令行安装，已更新elegantnote
![image](https://user-images.githubusercontent.com/26919925/92595070-5cad3600-f2d6-11ea-8563-120e48124f0b.png)

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantBook/issues/106

**Comment by tiange1949** [comment]
- 版本是texlive2020
![image](https://user-images.githubusercontent.com/26919925/92595783-7733df00-f2d7-11ea-8c51-589eea1afae6.png)

- 正在更新所有宏包
![image](https://user-images.githubusercontent.com/26919925/92595815-83b83780-f2d7-11ea-8ac6-972c3a87e280.png)

**Comment by EthanDeng** [comment]
虽然这个网站很久没更新了，但是上面的 minimal example 仍然是可以编译的，你更新完之后，如果还有问题，把你的报错信息以发上来看下吧。

```tex
\documentclass[geye,green,pad,en]{elegantnote}

\title{A Note Example}
\author{ddswhu}
\institute{Elegant\LaTeX{} Program}
\version{1.00}
\date{\today}

\begin{document}

\maketitle

\section{Introduction}
Example Text.

\end{document}
```

**Comment by tiange1949** [comment]
> 虽然这个网站很久没更新了，但是上面的 minimal example 仍然是可以编译的，你更新完之后，如果还有问题，把你的报错信息以发上来看下吧。
> 
> ```
> \documentclass[geye,green,pad,en]{elegantnote}
> 
> \title{A Note Example}
> \author{ddswhu}
> \institute{Elegant\LaTeX{} Program}
> \version{1.00}
> \date{\today}
> 
> \begin{document}
> 
> \maketitle
> 
> \section{Introduction}
> Example Text.
> 
> \end{document}
> ```

![image](https://user-images.githubusercontent.com/26919925/92691696-8a958780-f375-11ea-8d5b-ed4c1377daa6.png)

**Comment by EthanDeng** [comment]
#28
