### ISSUE TITLE
按照教程更新了texlive的所有宏包，现在所有的文件都无法编译了

### ISSUE THREAD

**Issue by tiange1949** [ElegantLaTeX/ElegantNote#28]
- 编译引擎试了xelatex和pdflatex
-一直显示这个错误，无法消除
-google了也没有找到解决办法
![image](https://user-images.githubusercontent.com/26919925/92691401-1955d480-f375-11ea-89c3-013a4f40062e.png)

**Comment by sikouhjw** [comment]
可能是更新不成功，`texdoc install-LaTeX`，使用更新中断情况的命令，如果再次更新后还不行，看 https://github.com/CTeX-org/forum/issues/119 ，如果还不行，换镜像源再更新

**Comment by tiange1949** [comment]
> 可能是更新不成功，`texdoc install-LaTeX`，使用更新中断情况的命令，如果再次更新后还不行，看 [CTeX-org/forum#119](https://github.com/CTeX-org/forum/issues/119) ，如果还不行，换镜像源再更新

- 在更新前已更换清华镜像源

- 更新过程中没有中断

- 更新结束后显示已经更新完成了

**Comment by sikouhjw** [comment]
> > 可能是更新不成功，`texdoc install-LaTeX`，使用更新中断情况的命令，如果再次更新后还不行，看 [CTeX-org/forum#119](https://github.com/CTeX-org/forum/issues/119) ，如果还不行，换镜像源再更新
> 
> * 在更新前已更换清华镜像源
> * 更新过程中没有中断
> * 更新结束后显示已经更新完成了

清华源最近不好用，换一个

**Comment by sikouhjw** [comment]
即使更新没有中断，也不代表全部更新成功

> > 可能是更新不成功，`texdoc install-LaTeX`，使用更新中断情况的命令，如果再次更新后还不行，看 [CTeX-org/forum#119](https://github.com/CTeX-org/forum/issues/119) ，如果还不行，换镜像源再更新
> 
> * 在更新前已更换清华镜像源
> * 更新过程中没有中断
> * 更新结束后显示已经更新完成了

**Comment by tiange1949** [comment]
> 即使更新没有中断，也不代表全部更新成功
> 
> > > 可能是更新不成功，`texdoc install-LaTeX`，使用更新中断情况的命令，如果再次更新后还不行，看 [CTeX-org/forum#119](https://github.com/CTeX-org/forum/issues/119) ，如果还不行，换镜像源再更新
> > 
> > 
> > 
> > * 在更新前已更换清华镜像源
> > * 更新过程中没有中断
> > * 更新结束后显示已经更新完成了

- 刚才又运行了`tlmgr update --self --all`命令，结果如下
![image](https://user-images.githubusercontent.com/26919925/92692512-dd237380-f376-11ea-82a4-a1984031b8fb.png)

**Comment by tiange1949** [comment]
⚡ Longhui@DELL  ~\scoop\apps\windows-terminal\current               [15:02]
❯ tlmgr update --self --all
tlmgr.pl: package repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr.pl: saving backups to C:/texlive/2020/tlpkg/backups
tlmgr.pl: skipping forcibly removed package: xindex

**Comment by tiange1949** [comment]
**一直显示这个`Missing \begin{document}. \ExplLoaderFileDate{expl3.sty}}`错误，google了一下，这个expl3.sty好像是LaTeX3的一个包，不是LaTeX2e的，说好像缺少依赖，但是也没找到解决的办法**

**Comment by sikouhjw** [comment]
> **一直显示这个`Missing \begin{document}. \ExplLoaderFileDate{expl3.sty}}`错误，google了一下，这个expl3.sty好像是LaTeX3的一个包，不是LaTeX2e的，说好像缺少依赖，但是也没找到解决的办法**

你按我说的走一遍可以吗

**Comment by tiange1949** [comment]
- 跳转到错误行，texstudio自动打开了`expl3.sty`这个文件，界面如下：
![image](https://user-images.githubusercontent.com/26919925/92693256-f0830e80-f377-11ea-9055-bed53b07198c.png)

**Comment by tiange1949** [comment]
- 第1步，`tlmgr update --reinstall-forcibly-removed --all`已执行
![image](https://user-images.githubusercontent.com/26919925/92693702-8cad1580-f378-11ea-965c-ecb2577559ac.png)

- 重启texstudio,再编译原文件，仍没通过
![image](https://user-images.githubusercontent.com/26919925/92693870-ca11a300-f378-11ea-95cb-35e2b2d973ff.png)

**Comment by tiange1949** [comment]
- 第2步，按照 CTeX-org/forum#119提示，更新format， `fmtutil-sys --all`，**已执行**；
![image](https://user-images.githubusercontent.com/26919925/92694201-499f7200-f379-11ea-85ff-b2446a23529f.png)
- 重启texstudio，再编译原文件；
![image](https://user-images.githubusercontent.com/26919925/92694395-95521b80-f379-11ea-885e-692060ac25d4.png)

**- 终于编译成功了，非常感谢大佬！！！！**

**Comment by liubenyuan** [comment]
谢谢！我执行`fmtutil-sys --all`不行，后尝试执行`fmtutil-user --all`之后可以的。也是更新中断导致的。

**Comment by asmwarrior** [comment]
我也是同样的问题：
我今天装了一个全新的TexLive2020（Win7系统，安装texlive我选择的是portable模式），然后更新了一下，我更新中断过一次网络（就是前面大家说的更新中断）。
试了前面讨论的所有方法，都不行，现在只能删掉文件夹，重新安装和重新更新，不知道一会儿更新结束之后是否能成功。

**更新**：重新安装和重新更新，之后就能用了。
