### ISSUE TITLE
实现对公式加框的方法\boxed{}

### ISSUE THREAD

**Issue by AGJackie** [ElegantLaTeX/ElegantNote#29]
在书写一长段公式时，有时需要对部分公式加框以标注出重点，可采用 amsmath 里的 `\boxed{}` 命令

例如：
```
\[
\begin{aligned}
E\left[S_{n}\right] &=\prod_{t=1}^{n} E\left[\left(1+i_{t}\right)\right] \\
&=\prod_{t=1}^{n}\left(1+E\left[i_{t}\right]\right) \\
&=\boxed{(1+j)^{n}}
\end{aligned}
\]
```

效果图如下：
![shili](https://user-images.githubusercontent.com/49231906/93658554-2490ba80-fa6f-11ea-8c71-e513c9eac220.jpg)

参考链接：
[\boxed{}, TikZ and colored equation background](https://tex.stackexchange.com/questions/75129/boxed-tikz-and-colored-equation-background)
[怎么构建方框？](https://www.zhihu.com/question/268567905/answer/339255525)

**Comment by AGJackie** [comment]
如果需要着色，可以用\colorbox或者\fcolorbox

例如：
```
\[
\begin{aligned}
\fcolorbox{blue}{yellow}{$E\left[S_{n}\right]$} &=\prod_{t=1}^{n} E\left[\left(1+i_{t}\right)\right] \\
&=\colorbox{yellow}{$\prod_{t=1}^{n}\left(1+E\left[i_{t}\right]\right) $}\\
&=\boxed{(1+j)^{n}}
\end{aligned}
\]
```
效果图如下：

![lizi2](https://user-images.githubusercontent.com/49231906/93659629-c4ebdc80-fa79-11ea-8ac9-b712aed83985.jpg)

**Comment by AGJackie** [comment]
还有一种方法，见[Border color only on boxed equation](https://tex.stackexchange.com/questions/522350/border-color-only-on-boxed-equation)

**Comment by EthanDeng** [comment]
`\colorbox` 这个方法可能更加有应用场景。
