### ISSUE TITLE
MacOS 编译出错

### ISSUE THREAD

**Issue by jiyiren** [ElegantLaTeX/ElegantNote#3]
* 系统：MacOS Mojave，版本 10.14.3
* LaTeX 环境：TexLive 2018( 对应 [MacTeX 20180417](https://www.tug.org/mactex/) 版本)
* LaTeX 编辑器：TeXMaker，编译方法 XeLaTeX
* 编译 ElegantNote 中文和英文版均出现问题，如下图，看似缺少字体。在编译 ElegantBook 也有此问题。
      ![](http://img.godjiyi.cn/jy_20190414231536.png)

* 但编译 ElegantArticle 中文没有问题。

能否解决 MacOS 以及其他 Linux 比如 Ubuntu 上的模板问题呢？希望能跨平台，字体可以用通用字体，或者能配置在仓库里？

**Comment by EthanDeng** [comment]
ElegantArticle 是指的是 ElegantPaper 吗？为了保证跨系统没问题，Book 和 Paper 其实都已经改过字体了，应该这两个都不会出问题的。Note 因为处于挂机状态，在修改封面，字体的还没修改，如果需要，我明天先把这部分先传上来。

**Comment by EthanDeng** [comment]
@jiyiren 你试下

**Comment by EthanDeng** [comment]
@jiyiren 我把改过的文件发上来了，你再试下。Book 的错误信息再提供下，你提供的 Note 的错误信息是宋体字体问题，但是 Book 里面已经没有这个了。

**Comment by Cadden** [comment]
LaTeX 环境:ctex, LaTeX 编辑器 WinEdt6.0, Package keyval Error: setkeys undefined.请问这个问题怎么解决呢

**Comment by EthanDeng** [comment]
> LaTeX 环境:ctex, LaTeX 编辑器 WinEdt6.0, Package keyval Error: setkeys undefined.请问这个问题怎么解决呢

是 Note 吗？

**Comment by Liam0205** [comment]
> LaTeX 环境:ctex, LaTeX 编辑器 WinEdt6.0, Package keyval Error: setkeys undefined.请问这个问题怎么解决呢

这个模板不支持老旧的 CTeX 套装。

你的问题也与这个 issue 无关。

**Comment by jiyiren** [comment]
* **ElegantNote** 源码下下来可以编译通过了，之前都是在仓库的 **Release** 里下载，感谢@EthanDeng：
   ![](http://img.godjiyi.cn/jy_20190415124550.png)

* **ElegantBook** 我是在源码库的 **Release** 里下的 **3.06** 版本编译出错的，我直接下源码就没有错误，建议发布一个新版本吧：
  * **ElegantBook 3.06**  出错界面：
  ![](http://img.godjiyi.cn/jy_20190415124102.png)
  * **ElegantBook** 仓库最新源码，编译通过：
   ![](http://img.godjiyi.cn/jy_jy_20190415124407.jpg)

* **ElegantPaper** 用仓库源码也编译的很顺畅了，感谢作者

**Comment by jiyiren** [comment]
@EthanDeng 谢谢！

**Comment by EthanDeng** [comment]
Paper 是前段时间更新完的。Book 从 3.06 之后一直不断有 fix，而且涉及到比较大的改动，所以会晚一些时间再发布 release。 Note 在 Paper 更新之后，还没来得及改，昨天临时把部分内容传上来了，后面还要再加其他东西才会 release。

所以，**强烈建议你使用最新版本**，如果在使用仓库最新版之后仍然有问题，你可以提交 issue，发邮件给我们。

**Comment by jiyiren** [comment]
OK 👌
