### ISSUE TITLE
考虑一下发一个Lyx模板，所见即所得，门槛低很多

### ISSUE THREAD

**Issue by lon91ong** [ElegantLaTeX/ElegantNote#30]
如题，希望能考虑一下
[Lyx官方](https://www.lyx.org/)

**Comment by Liam0205** [comment]
这么多年了 LyX 还就是个半成品……

基本上国内的模板，都没有考虑兼容 LyX。主要就是因为 LyX 是个半成品，模板作者自己不用，那为啥要为别人开发一个模板？你得知道，这些开源的东西，基本上最开始都是作者自己想要，然后开发了觉得好，就改吧改吧然后开源。
