### ISSUE TITLE
不能通过bibtex引用参考文献？

### ISSUE THREAD

**Issue by hjnnjh** [ElegantLaTeX/ElegantNote#31]
报错如下
![image](https://user-images.githubusercontent.com/37699150/94440182-efedd300-01d3-11eb-9daa-e4306d8bcb3e.png)

**Comment by EthanDeng** [comment]
中间文件导致的提示信息，编译多次就没有了。

**Comment by haharong9** [comment]
为啥参考文献编译不出来，报错如下，感谢您！
![5fc3db0caf68623ce9848fe037ff5daf](https://github.com/user-attachments/assets/4a4d93be-183e-4e81-9cb7-6672f7fced6f)
