### ISSUE TITLE
\mathbb{} and \mathscr{} can not be used

### ISSUE THREAD

**Issue by beyes** [ElegantLaTeX/ElegantNote#33]
as the title

**Comment by sikouhjw** [comment]
MWE呢？

**Comment by sikouhjw** [comment]
这是 LaTeX 基础的问题，麻烦去读 `texdoc lshort-zh-cn`
```tex
\documentclass{elegantnote}
\usepackage{amssymb,mathrsfs}
\begin{document}
  $\mathbb{A}, \mathscr{A}$
\end{document}
```

**Comment by beyes** [comment]
我并非不知道可以这样，因为报错是我没有引用宏包。就像你们把字体支持放到了模版类一样，把对黑板体和手写字体的支持放到模版类中是不是更好，\mathcal{} 是可以的。

________________________________
发件人: sikouhjw <notifications@github.com>
发送时间: Friday, November 20, 2020 11:17:44 AM
收件人: ElegantLaTeX/ElegantNote <ElegantNote@noreply.github.com>
抄送: wenjie ye <wenjie_ye@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [ElegantLaTeX/ElegantNote] \mathbb{} and \mathscr{} can not be used (#33)


这是 LaTeX 基础的问题，麻烦去读 texdoc lshort-zh-cn

\documentclass{elegantnote}

\usepackage{amssymb,mathrsfs}

\begin{document}

  $\mathbb{A}, \mathscr{A}$

\end{document}

―

**Comment by sikouhjw** [comment]
> 
> 我并非不知道可以这样，因为报错是我没有引用宏包。就像你们把字体支持放到了模版类一样，把对黑板体和手写字体的支持放到模版类中是不是更好，\mathcal{} 是可以的。

那你应该是「提意见」而不是「问报错」，你只写个标题谁知道你的意思？

**Comment by beyes** [comment]
这个确实是我的问题，我是第一次提交这个，我错误的以为那里就是提意见的，很抱歉，只写个标题也是我的问题，以后会好好写，谢谢。

________________________________
发件人: sikouhjw <notifications@github.com>
发送时间: Friday, November 20, 2020 11:29:48 AM
收件人: ElegantLaTeX/ElegantNote <ElegantNote@noreply.github.com>
抄送: wenjie ye <wenjie_ye@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [ElegantLaTeX/ElegantNote] \mathbb{} and \mathscr{} can not be used (#33)


我并非不知道可以这样，因为报错是我没有引用宏包。就像你们把字体支持放到了模版类一样，把对黑板体和手写字体的支持放到模版类中是不是更好，\mathcal{} 是可以的。

那你应该是「提意见」而不是「问报错」，你只写个标题谁知道你的意思？

―

**Comment by EthanDeng** [comment]
好的，之后增加模板所用宏包说明。
