### ISSUE TITLE
可以考虑增加思源字体族的选项

### ISSUE THREAD

**Issue by xiaoxuan-yu** [ElegantLaTeX/ElegantNote#34]
方正系列字体虽然允许免费商用，但是设计时间比较久远，不如一些现代字体美观。而Adobe提供的思源宋体和思源黑体是优秀的开源字体，除了授权上更加开放，也更加符合现代审美，更适合多语言混合排版等优点，希望可以考虑添加这一组预设。

**Comment by sikouhjw** [comment]
`texdoc ctex`，自己先看看吧

**Comment by EthanDeng** [comment]
可以自己设置字体（设置方法文档中有涉及）或者传递 ctex 的字体选项，本模板不考虑。
