### ISSUE TITLE
设置 en 后无法生成 pdf

### ISSUE THREAD

**Issue by louiswng** [ElegantLaTeX/ElegantNote#37]
问题：
设置 `\documentclass[cn,PC,12pt]{elegantnote}` 后，在 Texpad 上无法生成对应 PDF，但无 errors 或 warnings。
若设置 `\documentclass[en,PC,12pt]{elegantnote}`，则输入中文为乱码。

系统：
OS: MacOS Big Sur 11.6
elegantnote: 2.3.0
Texpad: 1.9.6

**Comment by sikouhjw** [comment]
提供 `tex`、`log`、`pdf` 文件

**Comment by louiswng** [comment]
> 提供 `tex`、`log`、`pdf` 文件

我直接使用你们 github 中的 .tex 和 .cls 文件

无 errors 或 warnings --> 没有 log

[test.pdf](https://github.com/ElegantLaTeX/ElegantNote/files/7365429/test.pdf)

**Comment by sikouhjw** [comment]
> > 提供 `tex`、`log`、`pdf` 文件
> 
> 我直接使用你们 github 中的 .tex 和 .cls 文件
> 
> 无 errors 或 warnings --> 没有 log
> 
> [test.pdf](https://github.com/ElegantLaTeX/ElegantNote/files/7365429/test.pdf)

任何编译行为都会有 `log` 文件。
