### ISSUE TITLE
中文模板显示英文的日期格式

### ISSUE THREAD

**Issue by sierxue** [ElegantLaTeX/ElegantNote#4]
系统: ubuntu 18.04; 语言：English; 格式：中国

在更新处，显示的是英文格式：July 18, 2019.

请问，怎么在我现有的系统、语言、格式的设定情况下，把时间格式改为中文格式？

谢谢！

**Comment by EthanDeng** [comment]
由于 `lang=en` 时，没有载入中文宏包，所以，你需要中文日期的话，直接写是有问题的。

方法是，你先载入中文宏包
```tex
\usepackage[UTF8,scheme=plain]{ctex}
```
然后，把日期格式改为中文的话有两种方式

1. 直接写 `\date{2019 年 7 月 24 日}`
2. 用 `ctex` 宏集里面的 `\zhtoday` 命令（来源于 `zhnumber` 宏包），具体写法为
`\date{\zhtoday}`
