### ISSUE TITLE
请问定理样式是否可以增加“结论”？

### ISSUE THREAD

**Issue by carbonshow** [ElegantLaTeX/ElegantNote#43]
如题，目前有：
- theorem
- lemma
- proposition
- corollary

能否增加结论，说明总结或结果。

**Comment by sikouhjw** [comment]
可以仿写
https://github.com/ElegantLaTeX/ElegantNote/blob/23c5a00e65ace8c306954441ac2fdbb29a65c9b9/elegantnote.cls#L172-L197
