### ISSUE TITLE
选项[math=mtpro2]似乎没有效果

### ISSUE THREAD

**Issue by JouderMin** [ElegantLaTeX/ElegantNote#44]
我在使用 ElegantNote 时使用了 math=mtpro2 选项以启用 mtpro2 字体，但在输出的 pdf 中公式仍然为默认的 cm 字体。

我使用的 LaTeX 引擎为 XeLaTeX，TeXLive 2022，ElegantNote 版本 2.40。

ElegantPaper 与 ElegantBook 正常启用了 mtpro2。

**Comment by EthanDeng** [comment]
我刚看了下，好像没加到，下次更新我加进去，谢谢反馈！

**Comment by sikouhjw** [comment]
可以加这段代码，当然你需要使用 `math=mtpro2` 来避免模板对数学字体的操作
https://github.com/ElegantLaTeX/ElegantBook/blob/99eb12f4c44e11261dc1b69e62f2c182ef0898c8/elegantbook.cls#L160-L163
