### ISSUE TITLE
提请护眼模式添加淡黄色纸张

### ISSUE THREAD

**Issue by zhiyuanzhai** [ElegantLaTeX/ElegantNote#45]
像是这个颜色：
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/37478391/170883285-6cf36554-1d2c-489a-9072-b319e73e1d1f.png">

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantNote/blob/23c5a00e65ace8c306954441ac2fdbb29a65c9b9/elegantnote-cn.tex#L52-L56
