### ISSUE TITLE
是否考虑支持16:9

### ISSUE THREAD

**Issue by Zissi-Lei** [ElegantLaTeX/ElegantNote#46]

**Comment by Zissi-Lei** [comment]
你好，请问你们是否有考虑支持16:9的PPT模式？

**Comment by Zissi-Lei** [comment]
你好，请问你们是否有考虑支持16:9的PPT模式？

**Comment by sikouhjw** [comment]
可以根据
https://github.com/ElegantLaTeX/ElegantNote/blob/23c5a00e65ace8c306954441ac2fdbb29a65c9b9/elegantnote.cls#L373-L381
自己写页面设置
