### ISSUE TITLE
与 wrapfig2 的宏包兼容性？

### ISSUE THREAD

**Issue by perrogg** [ElegantLaTeX/ElegantNote#47]
偶然发现，在使用 elegantnote 文档类搭配 wrapfig2 宏进行文字绕排时，编译报错如下：

`No counter 'chapter' defined. }(}`

但能生成pdf。如图所示
<img width="1349" alt="note" src="https://user-images.githubusercontent.com/14990848/186304214-5b927835-e80e-4dc7-81be-c30ad1e991be.png">
<img width="740" alt="error" src="https://user-images.githubusercontent.com/14990848/186304225-9800638f-a231-4c95-9f7f-c555e55abd85.png">

MWE：

```
\documentclass[cn]{elegantnote}
\usepackage{wrapfig2}
\usepackage{zhlipsum}
\begin{document}
	\zhlipsum[1]
	\begin{wrapfigure}{r}{0.35\textwidth}
	\centering\unitlength=1mm
	\begin{picture}(40,30)
		\polygon(0,0)(40,0)(40,30)(0,30)
		\Line(0,0)(40,30)\Line(0,30)(40,0)
	\end{picture}
	\caption{book test}
	\end{wrapfigure}
\zhlipsum[2]
\end{document}
```

但如果仅仅将 note 改为 paper 或 book 文档类，不报错，如下图：

<img width="1352" alt="paper" src="https://user-images.githubusercontent.com/14990848/186304408-0113648f-d920-4f93-b4c8-3f7ed0cdeb6e.png">
<img width="1350" alt="book" src="https://user-images.githubusercontent.com/14990848/186304423-04beb9cf-a636-424c-8452-d7f5be46e145.png">

**Comment by sikouhjw** [comment]
这个问题可以简化为下面这段代码
```tex
\documentclass{elegantnote}
\usepackage{float}
\newfloat{text}{tbp}{lotx}[chapter]

\begin{document}
  test
\end{document}
```
是 `wrapfig2` 调用了 `float` 宏包的 `\newfloat` 命令，而 `\newfloat` 命令报了错。

受 `texdoc float` sec 4.1 Basics 的 44-46 行代码的提示，可以在代码中加上
```tex
\makeatletter
\newcounter{chapter}\@namedef{thechapter}{\arabic{chapter}}
\makeatother
```
那么
```tex
\documentclass[cn]{elegantnote}
\makeatletter
\newcounter{chapter}\@namedef{thechapter}{\arabic{chapter}}
\makeatother
\usepackage{wrapfig2}
\usepackage{zhlipsum}
\begin{document}
  \zhlipsum[1]
  \begin{wrapfigure}{r}{0.35\textwidth}
  \centering\unitlength=1mm
  \begin{picture}(40,30)
    \polygon(0,0)(40,0)(40,30)(0,30)
    \Line(0,0)(40,30)\Line(0,30)(40,0)
  \end{picture}
  \caption{book test}
  \end{wrapfigure}
\zhlipsum[2]
\end{document}
```
