### ISSUE TITLE
默认的参考文献格式好像不是apa

### ISSUE THREAD

**Issue by PzzAg6** [ElegantLaTeX/ElegantNote#48]
使用biblatex和biber

reference.bib:

```
@article{irnich_path-reduced_2010,
	title = {Path-Reduced Costs for Eliminating Arcs in Routing and Scheduling},
	volume = {22},
	issn = {1091-9856},
	url = {https://pubsonline.informs.org/doi/10.1287/ijoc.1090.0341},
	doi = {10.1287/ijoc.1090.0341},
	abstract = {In many branch-and-price algorithms, the column generation pricing problem consists of computing feasible paths in a network. In this paper, we show how, in this context, path-reduced costs can be used to remove some arcs from the underlying network without compromising optimality, and we introduce a bidirectional search technique to compute these reduced costs. This arc elimination method can lead to a substantial speedup of the pricing process and the overall branch-and-price algorithm. Special attention is given to variants of shortest-path problems with resource constraints. Computational results obtained for the vehicle routing problem with time windows show the efficiency of the proposed method.},
	pages = {297--313},
	number = {2},
	journaltitle = {{INFORMS} Journal on Computing},
	author = {Irnich, Stefan and Desaulniers, Guy and Desrosiers, Jacques and Hadjar, Ahmed},
	urldate = {2022-08-31},
	date = {2010-05},
	note = {Publisher: {INFORMS}},
	keywords = {vehicle routing, branch and bound, column generation and variable elimination, integer programming},
	
}
@article{hadjar_branch-and-cut_2006,
	title = {A Branch-and-Cut Algorithm for the Multiple Depot Vehicle Scheduling Problem},
	volume = {54},
	issn = {0030-364X},
	url = {https://pubsonline.informs.org/doi/abs/10.1287/opre.1050.0240},
	doi = {10.1287/opre.1050.0240},
	abstract = {We consider the multiple depot vehicle scheduling problem ({MDVSP}) and propose a branch-and-bound algorithm for solving it that combines column generation, variable fixing, and cutting planes. We show that the solutions of the linear relaxation of the {MDVSP} contain many “odd cycles.” We derive a class of valid inequalities by extending the notion of odd cycle and describe a lifting procedure for these inequalities. We prove that the lifted inequalities represent, under certain conditions, facets of the underlying polytope. Finally, we present the results of a computational study comparing several strategies (variable fixing, cutting planes, mixed branching, and tree search) for solving the {MDVSP}.},
	pages = {130--149},
	number = {1},
	journaltitle = {Operations Research},
	author = {Hadjar, Ahmed and Marcotte, Odile and Soumis, François},
	urldate = {2022-09-12},
	date = {2006-02},
	note = {Publisher: {INFORMS}},
	keywords = {algorithms, branch-and-cut algorithm for the {MDVSP}, cutting plane/facet, integer, multicommodity, multicommodity formulation, multiple depot vehicle scheduling problem, networks/graphs, programming, scheduling, transportation, vehicles},
	
}
```

使用默认的格式，并设定为authoryear：
`\documentclass[cn,hazy,blue,14pt,screen, citestyle = authoryear]{elegantnote}`

得到的引文和引文目录是：
Hadjar, Marcotte, and Soumis 2006
Irnich et al. 2010

[1] Ahmed Hadjar, Odile Marcotte, and François Soumis. “A Branch-and-Cut Algorithm for the Multiple Depot Vehicle Scheduling Problem”. In: Operations Research 54.1 (Feb. 2006). Publisher: INFORMS, pp. 130–149. ISSN: 0030-364X. DOI: 10.1287/opre.1050.0240. URL: https://pubsonline. informs.org/doi/abs/10.1287/opre.1050.0240 (visited on 09/12/2022).
[2] Stefan Irnich et al. “Path-Reduced Costs for Eliminating Arcs in Routing and Scheduling”. In: INFORMS Journal on Computing 22.2 (May 2010). Publisher: INFORMS, pp. 297–313. ISSN: 1091-9856. DOI: 10.1287/ijoc.1090.0341. URL: https://pubsonline.informs.org/doi/10.1287/ ijoc.1090.0341 (visited on 08/31/2022).

而正确的apa格式是：
Hadjar et al. 2006
Irnich et al. 2010

Hadjar, A., Marcotte, O., & Soumis, F. (2006). A branch-and-cut algorithm for the multiple depot vehicle scheduling problem [Publisher: INFORMS]. Opera- tions Research, 54(1), 130–149. https://doi.org/10.1287/opre.1050.0240
Irnich, S., Desaulniers, G., Desrosiers, J., & Hadjar, A. (2010). Path-reduced costs for eliminating arcs in routing and scheduling [Publisher: INFORMS]. INFORMS Journal on Computing, 22(2), 297–313. https://doi.org/10.1287/ijoc.1090.0341

当我把`bibstyle`修改为apa时，即：
`\documentclass[cn,hazy,blue,14pt,screen, bibstyle = apa, citestyle = authoryear]{elegantnote}`
才出现正确的引文目录

不知道是我的问题还是其他什么地方出了什么问题

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantNote/blob/23c5a00e65ace8c306954441ac2fdbb29a65c9b9/elegantnote.cls#L47-L48
`bibstyle` 的默认值不是 `apa`
