### ISSUE TITLE
无法生成参考文献

### ISSUE THREAD

**Issue by sierxue** [ElegantLaTeX/ElegantNote#5]
我按照 ElegantPaper 的方式生成参考文献，但是无法成功实现。请问在 ElegantNote 下怎么生成参考文献？谢谢！

**Comment by EthanDeng** [comment]
你是中文模式的话，别忘了调用 `gbt7714` 宏包。具体的，你需要在导言区加入 `\usepackage{gbt7714}`，然后在末尾加入 `\bibliography{wpref}`。我自己测试了下没问题的。

几个需要注意的事情：

1. 你可以先用 `\nocite{*}` 放在 `\bibliography{wpref}` 之前测试下，但是正文引用请用 `\cite{...}`
2. 如果你想要更加精细的设置，比如多个参考文献[1][2][3] 变为 [1-3] 等等，请参考 `natbib` 和 `gbt7714` 的官方说明文档。
