### ISSUE TITLE
EN版本下definition环境中字体是斜体

### ISSUE THREAD

**Issue by m4p1e** [ElegantLaTeX/ElegantNote#51]
如题，正常来说应该不是斜体，我看definition的设置也是对的:
```
\ifdefstring{\ELEGANT@lang}{en}{
  \theoremstyle{plain}% default
  \newtheorem{theorem}{Theorem}[section] %
  \newtheorem{lemma}[theorem]{Lemma} %
  \newtheorem{proposition}[theorem]{Proposition} %
  \newtheorem*{corollary}{Corollary} %
  \theoremstyle{definition} %
  \newtheorem{definition}{Definition}[section] %
  \newtheorem{conjecture}{Conjecture}[section] %
  \newtheorem{example}{Example}[section] %
  \theoremstyle{remark} %
  \newtheorem*{remark}{Remark} %
  \newtheorem*{note}{Note} %
```
definition环境的style确实也是` \theoremstyle{definition}`但是为啥还是斜的呢？

![image](https://user-images.githubusercontent.com/38675350/197674043-c0ebcf83-2cbd-4c49-8c9e-32e4951a0875.png)

**Comment by m4p1e** [comment]
definition的theoremstyle被重新定义了，但是不知道为什么改成了斜体，而不是原来的roman字体

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantNote/blob/23c5a00e65ace8c306954441ac2fdbb29a65c9b9/elegantnote.cls#L284-L286
https://github.com/ElegantLaTeX/ElegantNote/blob/23c5a00e65ace8c306954441ac2fdbb29a65c9b9/elegantnote.cls#L127-L131
