### ISSUE TITLE
LaTeX Error: The key 'ctex/section' is unknown and is being ignored.

### ISSUE THREAD

**Issue by wooego** [ElegantLaTeX/ElegantNote#52]
想使用ctex的ctexset对section的格式进行设置，总是提示：The module 'ctex' does not have a key called 'ctex/section'

%!TEX program = xelatex
\documentclass[cn,hazy,black,14pt,normal]{elegantnote}
\usepackage[UTF8,heading=true]{ctex}
\usepackage{tcolorbox}
\ctexset{section={
    nameformat+=\sectionFormat
  }%
}%
\newcommand\sectionFormat[1]{%
  \tcbox[on line]{#1}%
}

\title{中国哲学简史\\%
	 A Short History of Chinese Philosophy\\%
}

\author{冯友兰}

\begin{document}
\maketitle  %生成标题
\section{中国哲学的精神}%第1章
\section{中国哲学的精神2}%第2章
\section{中国哲学的精神3}%第3章
\end{document}

**Comment by sikouhjw** [comment]
https://github.com/ElegantLaTeX/ElegantNote/blob/23c5a00e65ace8c306954441ac2fdbb29a65c9b9/elegantnote.cls#L117-L121
不支持用 `\ctexset` 去定制章节格式。
