### ISSUE TITLE
大佬，tableofcontents制作的目录中颜色能不能统一一下。

### ISSUE THREAD

**Issue by goodaniu** [ElegantLaTeX/ElegantNote#53]

**Comment by sikouhjw** [comment]
```tex
\documentclass{elegantnote}

\begin{document}
  \tableofcontents
  \section{test}
  \subsection{test}
  \subsubsection{test}
\end{document}
```
![图片](https://user-images.githubusercontent.com/49770925/206823744-afad8a43-cc75-4c30-96b5-7d7b5b9c4f64.png)
1. 哪里会报错？
2. 你觉得行距设多少美观？
3. 数字颜色和标题不匹配吗？

**Comment by goodaniu** [comment]
> 

对不起，是我的错，刚刚已经修改了issue，给您添麻烦了。
但是无法撤销issue,所以立刻修改了问题。
我做了些修改，改了页面尺寸后想着重设页眉页脚，所以报了些错，删除修改之后就没报错了。
```
%\geometry{papersize={72mm,160mm},left=6mm,right=6mm,bottom=6mm,top=14mm}
\fancyhf{}
\lfoot{\scriptsize\thepage}
\lhead{\scriptsize\leftmark}
```
这样一改，就会报错：`Package xcolor Error: Undefined color `ECOLOR'. ^^I\include{tex/files}`
至于颜色，就是目录上的页码是黑色的，其他不是。

**Comment by goodaniu** [comment]
> 

是我学艺不精的问题，没有先清空之前的样式，加上\pagestyle{empty}就好了，再次道歉。

**Comment by sikouhjw** [comment]
目录中的彩色是超链接。
```tex
\documentclass{elegantnote}
\hypersetup{%
  linktocpage=true,
}
\begin{document}
  \tableofcontents
  \section{test}
  \subsection{test}
  \subsubsection{test}
\end{document}
```
